# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("PGUSER") { `whoami`.strip } %>

development:
  <<: *default
  database: helm_crm_development

test:
  <<: *default
  database: helm_crm_test

production:
  <<: *default
  database: helm_crm_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>